<a href="https://colab.research.google.com/github/HexQuant/math-stat-ex/blob/main/Chapter_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from sympy import *

$D\zeta=M\zeta^2-(M\zeta)^2=?$

$D\zeta=M(\zeta-M\zeta)^2=M(\zeta^2-2\zeta M\zeta+(M\zeta)^2=\\=M\zeta^2-M(2\zeta M\zeta) +M(M\zeta)^2=\\
=M\zeta^2-2M\zeta M\zeta) +(M\zeta)^2=M\zeta^2-(M\zeta)^2$

In [ ]:
k = 5
n =k * 1000
sick = np.random.randint(2, size=n)


NameError: ignored

In [ ]:
from sympy.solvers import solve
from sympy import symbols
k, p = symbols('k p', positive =True)
m = Symbol('m', positive = True)
solve(1/k**2+(m)**k*ln(m), k)

NameError: ignored

Пример решения задач с использованием компьютерной алгебры **Sympy** из учебника: "Наглядная математическая статистика" М. Б. Лагутин. 7-е изд. 2019. ISBN 978-5-00101-642-7 .

# Глава 1

## Задача 1
$f(a)=M(\zeta-a)^2, a=M\zeta$

$M(\zeta^2-2\zeta a+a^2)=\\=
M\zeta^2-2M (\zeta a) +Ma^2$

$-2M(\zeta a)+Ma^2 \rightarrow min$

$-2M\zeta+2Ma$

$M\zeta = Ma$

## Задача 2
$M \bar \eta = M(\frac{1}{n}(\eta_1+...+\eta_n))=\\
=\frac{1}{n}(M\eta_1+...+M\eta_n)=0.5$

$D \bar \eta = D(\frac{1}{n}(\eta_1+...+\eta_n))=\\
=M\eta^2-(M\eta)^2=0.5-0.25=0.25$

$M\bar\eta=\int_0^1 dx=$

## Задача 3
$M\eta(n)=M max(\eta_1,...,\eta_n)=$

$F_1(x)=P(\eta_1\leq x)$

$F_{\eta(n)}(\eta_{(n)}\leq a)=\prod_{i=1}^{n}P(\eta_i \leq a) = a^n$

$M\eta_{(n)}=\int_0^1 a^n da=\frac{1}{n+1}a^{n+1}\\=\frac{1}{n+1}1^{n+1}$


$M\bar\eta\ = \int_0^1 a \cdot  F_{\eta} da = \\
=\int_0^1 a^{n+1} da = \frac{1}{n+1}\cdot a$


In [1]:
from sympy import *
a, n = symbols('a n', positive =True)
F = a**n
F

a**n

In [ ]:
f = diff(F, a)
f

a**n*n/a

In [ ]:
M = integrate(a*f, (a, 0, 1))
M

n/(n + 1)

In [ ]:
D = integrate(a**2*f,(a,0,1)) - M**2
D

-n**2/(n + 1)**2 + n/(n + 2)

In [ ]:
factor(D)

n/((n + 1)**2*(n + 2))

## Задача 4
$F(\mu =  a)=p\cdot \prod_{i=1}^a (1-p)=\\
=p\cdot (1-p)^a$

In [ ]:
# число неудач до появления первого успеха и вероятность успеха
p = symbols('p', positive=True)
mu, a = symbols('mu a', positive=True, Integer=True)
F = p*(1-p)**a 
F

p*(1 - p)**a

In [ ]:
s = Sum(F, (a,1,+oo)).doit()
print(s)

p*Piecewise(((1 - p)/p, Abs(p - 1) < 1), (Sum((1 - p)**a, (a, 1, oo)), True))


## Задача 5

In [ ]:
# Кол-во тестируемых в группе
k = symbols('k', positive=True, Integer=True)
# Вероятность обнаружения заболевания
p = symbols('p', positive= True) 
# Вероятность отсутствия заболевания
q = 1 - p
# Вероястность что группа больна и НЕ больна
pk, qk = 1 - q**k, q**k
# Число всевозможных комбинации больных и здоровых в больной группе
i = symbols('i', positive=True, Integer=True)
npk =  Sum(binomial(k, i), (i, 1, k))
# Кол-во необходимых тестов для одной группы, с учётом того, что
# если в больной группе не выявился больной на k-1 тест, то тест делать не надо
z = 1*  qk + pk * ((k+1) * (npk-1)/npk + k * 1/npk)
z

(1 - p)**k + (1 - (1 - p)**k)*(k/Sum(binomial(k, i), (i, 1, k)) + (k + 1)*(Sum(binomial(k, i), (i, 1, k)) - 1)/Sum(binomial(k, i), (i, 1, k)))

In [ ]:
# Кол-во необходимых тестов для группы из 2-х тестируемых
z2 = z.subs(k,2).doit()
z2

8/3 - 5*(1 - p)**2/3

In [ ]:
# Критерий по "p" при котором выгоднее тестировать группами чем по отдельности
crit = solve(z2<2,p).args[0]
crit.evalf()

p < 0.367544467966324

## Задача 6

In [ ]:
x, p = symbols('x, p', positive=True)

In [ ]:
H = 1+1/x-(1-p)**x
H

-(1 - p)**x + 1 + 1/x

In [ ]:
h = diff(H, x)*-1
h

(1 - p)**x*log(1 - p) + x**(-2)

In [ ]:
# Для док-ва подставим значение предпологаемого кореня и возьмём предел
a = h.subs(x,1/sqrt(p))
limit(a,p,0)

p + (1 - p)**(1/sqrt(p))*log(1 - p)

In [ ]:
simplify(H.subs(x, 1/sqrt(p)))

sqrt(p) - (1 - p)**(1/sqrt(p)) + 1

# Глава 2

## Задача 2

In [36]:
from numpy.random import rand
from numpy import all

In [90]:
n = 5
z = 20
eta = rand(z,n)
K = all((eta[:,:-1]>eta[:,1:]), axis=1).astype(int)*n
K

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
MK = K.mean()
MK

0.0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [53]:
eta[:,1:]

array([[0.65037395, 0.38543861, 0.12992304, 0.88554705, 0.03499421,
        0.08357769, 0.68588367, 0.21164597, 0.24724843, 0.38728923,
        0.87189735, 0.38008842, 0.05281222, 0.46828597, 0.36605225,
        0.77117209, 0.0890361 , 0.243087  , 0.18870302],
       [0.9284641 , 0.84252114, 0.50380787, 0.59574816, 0.10081265,
        0.4507446 , 0.35210383, 0.84201085, 0.00192529, 0.91124433,
        0.84755994, 0.12636299, 0.47752559, 0.50694515, 0.386417  ,
        0.26569058, 0.38494147, 0.18284973, 0.90557905],
       [0.19236691, 0.05765029, 0.65385596, 0.40019936, 0.39252078,
        0.3002059 , 0.99647469, 0.39972393, 0.60784098, 0.15164151,
        0.37133547, 0.06505265, 0.32191856, 0.39590013, 0.86709991,
        0.86910997, 0.09226275, 0.11445465, 0.52568277],
       [0.33101419, 0.31319165, 0.68295518, 0.2642173 , 0.84352099,
        0.3255614 , 0.99490444, 0.00828151, 0.87771603, 0.96581953,
        0.01509323, 0.4382917 , 0.48710478, 0.31794573, 0.85515559,
        0.029