<a href="https://colab.research.google.com/github/HexQuant/math-stat-ex/blob/main/Chapter_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Глава 2

## Задача 2

In [ ]:
from numpy.random import rand
from numpy import all

In [ ]:
n = 5
z = 20
eta = rand(z,n)
K = all((eta[:,:-1]>eta[:,1:]), axis=1).astype(int)*n
K

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
MK = K.mean()
MK

0.0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [ ]:
eta[:,1:]

array([[0.65037395, 0.38543861, 0.12992304, 0.88554705, 0.03499421,
        0.08357769, 0.68588367, 0.21164597, 0.24724843, 0.38728923,
        0.87189735, 0.38008842, 0.05281222, 0.46828597, 0.36605225,
        0.77117209, 0.0890361 , 0.243087  , 0.18870302],
       [0.9284641 , 0.84252114, 0.50380787, 0.59574816, 0.10081265,
        0.4507446 , 0.35210383, 0.84201085, 0.00192529, 0.91124433,
        0.84755994, 0.12636299, 0.47752559, 0.50694515, 0.386417  ,
        0.26569058, 0.38494147, 0.18284973, 0.90557905],
       [0.19236691, 0.05765029, 0.65385596, 0.40019936, 0.39252078,
        0.3002059 , 0.99647469, 0.39972393, 0.60784098, 0.15164151,
        0.37133547, 0.06505265, 0.32191856, 0.39590013, 0.86709991,
        0.86910997, 0.09226275, 0.11445465, 0.52568277],
       [0.33101419, 0.31319165, 0.68295518, 0.2642173 , 0.84352099,
        0.3255614 , 0.99490444, 0.00828151, 0.87771603, 0.96581953,
        0.01509323, 0.4382917 , 0.48710478, 0.31794573, 0.85515559,
        0.029